import json
from core.types.contexts import NPCContext
from api.schemas import ComposedDialogue, DialogueOptionsSchema, QuestChoiceSchema
from core.types.contexts import Quest

class DialogueOutputComposer:

    @staticmethod
    def compose_dialogue(npc_context: NPCContext, raw_dialogue_output: str) -> ComposedDialogue:
        """
        Parses the JSON string returned by the LLM (conforming to the
        schema generated by _build_output_schema) and extracts the
        information needed to build the ComposedDialogue.
        """
        try:
            data = json.loads(raw_dialogue_output)
        except json.JSONDecodeError as e:
            raise ValueError(f"LLM output is not valid JSON: {e}\nRaw output: {raw_dialogue_output}") from e

        if not isinstance(data, dict):
            raise ValueError(f"Expected JSON output to be an object, got: {type(data)}")

        dialogue_text = data.get("dialogue")
        if not isinstance(dialogue_text, str):
            raise ValueError(f"Missing or invalid 'dialogue' field in output: {data}")

        player_options = data.get("player_options") or {}
        if not isinstance(player_options, dict):
            raise ValueError(f"Invalid 'player_options' field in output: {player_options}")

        dialogue_options = player_options.get("dialogue_options")
        accept = player_options.get("accept")
        refuse = player_options.get("refuse")

        intent = npc_context.intent

        parsed_options = None
        if player_options:
            if isinstance(intent, Quest):
                # Minimal consistency check: accept/refuse only make sense for a Quest with a choice
                if accept is not None or refuse is not None:
                    parsed_options = QuestChoiceSchema(
                        accept=accept,
                        refuse=refuse,
                        dialogue_options=dialogue_options
                    )
            else:
                if dialogue_options is not None:
                    parsed_options = DialogueOptionsSchema(
                        dialogue_options=dialogue_options
                    )

        return ComposedDialogue(
            intent=intent,
            dialogue=dialogue_text,
            player_options=parsed_options
        )