# Semantic constraints for Game Context (TODO: Move inside CONFIG).
MIN_EPOCH_LENGTH = 2
MAX_EPOCH_LENGTH = 1000
MAX_ENVIRONMENT_LENGTH = 2000
MAX_WORLD_STATE_LENGTH = 3000
MAX_MAIN_CHARACTER_DESCRIPTION_LENGTH = 2000

# Semantic constraints for NPC Context — (TODO: Move inside CONFIG).
MIN_NAME_LENGTH = 2
MAX_NAME_LENGTH = 100
MIN_AGE = 0
MAX_AGE = 10_000
MAX_PERSONALITY_LENGTH = 1000
MAX_CONTEXT_LENGTH = 1000
MAX_RELATION_LENGTH = 500
MAX_RECENT_PLOT_LENGTH = 2000
MAX_VISUAL_DESCRIPTION_LENGTH = 2000
MAX_BACKSTORY_LENGTH = 5000
MAX_LANGUAGE_ENTRIES = 10
MAX_QUEST_NAME_LENGTH = 150
MAX_QUEST_OBJECTIVE_LENGTH = 500
MAX_QUEST_DESCRIPTION_LENGTH = 3000
MAX_QUEST_LOCATION_LENGTH = 200
MAX_QUEST_REWARD_LENGTH = 300
MAX_MUST_USE_EXPRESSION_LENGTH = 1000
MAX_MORE_INFO_LENGTH = 1000

CHARS_PER_TOKEN = 4.0
"""Rough estimate of the number of characters per single token"""

LOW_THRESHOLD = 0.35
"""Thresholds for classifing a task into LOW tier"""

HIGH_THRESHOLD = 0.7
"""Thresholds for classifing a task into HIGH tier"""